blank_issues_enabled: true
contact_links:
  - name: Ask a question ❓
    url: https://github.com/zetTtai/DnDCharacterSheet/discussions/new/choose
    about: Ask a question or request support for using the template