name: CICD - Deploy Development on Pull Request (main or stage)

on: 
  pull_request:
    branches: [ main, stage ]
    paths-ignore:
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md

permissions:
  id-token: write
  contents: read

jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true
      environmentName: Development

  deploy-development:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    needs: [ build ]
    with:
      environmentName: Development